description: Indiana limits resources to this amount when applying for the Temporary Assistance for Needy Families program.

values:
  2024-01-01: 1_000

metadata:
  unit: currency-USD
  period: month
  label: Indiana TANF resource limit at application
  reference:
    - title: 470 IAC 10.3-3-6 - Resource limits
      href: https://casetext.com/regulation/indiana-administrative-code/title-470-division-of-family-resources/article-103-tanf-program/rule-470-iac-103-3-tanf-eligibility-requirements/section-470-iac-103-3-6-resource-limits
    - title: Indiana FSSA - TANF Resource Limits
      href: https://www.in.gov/fssa/dfr/tanf-cash-assistance/about-tanf/
