description: Indiana limits resources to this amount when applying for the Temporary Assistance for Needy Families program.

values:
  2024-01-01: 1_000

metadata:
  unit: currency-USD
  period: month
  label: Indiana TANF resource limit at application
  reference:
    - title: Indiana FSSA - TANF Resource Limits
      href: https://www.in.gov/fssa/dfr/tanf-cash-assistance/about-tanf/
    - title: Indiana Code 12-14-1-1 - TANF Eligibility
      href: https://iga.in.gov/laws/2023/ic/titles/12
