description: Connecticut multiplies the taxable social security amount by this rate under the social security benefit adjustment.
values:
   2019-01-01: 0.25
metadata:
  unit: /1
  period: year
  label: Connecticut social security benefit adjustment rate
  reference:
    - title: 2023 Form CT-1040 Connecticut Resident Income Tax Return Instructions
      href: https://portal.ct.gov/-/media/DRS/Forms/2023/Income/2023-CT-1040-Instructions_1223.pdf#page=8
    - title: 2022 Form CT-1040 Connecticut Resident Income Tax Return Instructions
      href: https://portal.ct.gov/-/media/DRS/Forms/2022/Income/2022-CT-1040-Instructions_1222.pdf#page=8
    - title: Connecticut General Statutes, Chapter 229, Sec. 12-701(20)(B)(x)(IV)
      href: https://www.cga.ct.gov/current/pub/chap_229.htm#sec_12-701
