description: Missouri TANF maximum countable resources at initial application. After signing an Individual Employment Plan (IEP), this limit increases to $5,000.

metadata:
  unit: currency-USD
  period: month
  label: Missouri TANF resource limit at application
  reference:
    - title: 13 CSR 40-2.310(3) - Resource Limits
      href: https://www.law.cornell.edu/regulations/missouri/13-CSR-40-2-310
    - title: 0200.000.00 - Overview of the Temporary Assistance Program
      href: https://dssmanuals.mo.gov/temporary-assistance-case-management/0200-000-00/

values:
  
  1991-01-01: 1_000
