description: Social Security total benefits.
values:
  # Actual (SSA)
  1957-01-01: 7_404_000_000
  1958-01-01: 8_576_000_000
  1959-01-01: 10_298_000_000
  1960-01-01: 11_245_000_000
  1961-01-01: 12_749_000_000
  1962-01-01: 14_461_000_000
  1963-01-01: 15_427_000_000
  1964-01-01: 16_223_000_000
  1965-01-01: 18_311_000_000
  1966-01-01: 20_051_000_000
  1967-01-01: 21_417_000_000
  1968-01-01: 24_954_000_000
  1969-01-01: 26_767_000_000
  1970-01-01: 31_884_000_000
  1971-01-01: 37_197_000_000
  1972-01-01: 41_625_000_000
  1973-01-01: 51_508_000_000
  1974-01-01: 58_581_000_000
  1975-01-01: 67_022_000_000
  1976-01-01: 75_759_000_000
  1977-01-01: 84_667_000_000
  1978-01-01: 92_960_000_000
  1979-01-01: 104_359_000_000
  1980-01-01: 120_598_000_000
  1981-01-01: 140_995_000_000
  1982-01-01: 156_182_000_000
  1983-01-01: 166_745_000_000
  1984-01-01: 175_739_000_000
  1985-01-01: 186_075_000_000
  1986-01-01: 196_667_000_000
  1987-01-01: 204_106_000_000
  1988-01-01: 217_149_000_000
  1989-01-01: 230_882_000_000
  1990-01-01: 247_816_000_000
  1991-01-01: 268_162_000_000
  1992-01-01: 285_995_000_000
  1993-01-01: 302_368_000_000
  1994-01-01: 316_812_000_000
  1995-01-01: 332_554_000_000
  1996-01-01: 347_050_000_000
  1997-01-01: 361_952_000_000
  1998-01-01: 374_969_000_000
  1999-01-01: 385_765_000_000
  2000-01-01: 407_635_000_000
  2001-01-01: 431_931_000_000
  2002-01-01: 453_821_000_000
  2003-01-01: 470_778_000_000
  2004-01-01: 493_263_000_000
  2005-01-01: 520_748_000_000
  2006-01-01: 546_238_000_000
  2007-01-01: 584_939_000_000
  2008-01-01: 615_344_000_000
  2009-01-01: 675_482_000_000
  2010-01-01: 701_609_000_000
  2011-01-01: 725_103_000_000
  2012-01-01: 774_791_000_000
  2013-01-01: 812_259_000_000
  2014-01-01: 848_463_000_000
  2015-01-01: 886_278_000_000
  2016-01-01: 911_384_000_000
  2017-01-01: 941_499_000_000
  2018-01-01: 988_635_000_000
  2019-01-01: 1_047_930_000_000
  2020-01-01: 1_095_924_000_000
  2021-01-01: 1_133_191_000_000
  2022-01-01: 1_231_707_000_000
  2023-01-01: 1_347_961_000_000
  # Projected (CBO)
  2024-01-01: 1_451_934_000_000
  2025-01-01: 1_549_110_000_000
  2026-01-01: 1_647_112_000_000
  2027-01-01: 1_740_634_000_000
  2028-01-01: 1_838_483_000_000
  2029-01-01: 1_938_394_000_000
  2030-01-01: 2_040_598_000_000
  2031-01-01: 2_146_676_000_000
  2032-01-01: 2_255_005_000_000
  2033-01-01: 2_364_405_000_000
  2034-01-01: 2_478_100_000_000
metadata:
  unit: currency-USD
  label: Social Security benefits
  reference:
    - title: Old-Age, Survivors, and Disability Insurance Trust Funds Cost
      # Benefit payments in bottom table.
      href: https://www.ssa.gov/oact/STATS/table4a3.html#fn1
    - title: CBO 10-Year Budget Projections (June 2024)
      # Source: https://www.cbo.gov/data/budget-economic-data#9
      # Table 1-4
      # Row 12: Subtotal, Social Security
      href: https://www.cbo.gov/system/files/2024-06/51118-2024-06-Budget-Projections.xlsx
