name: Test that Jupyter-Book builds
on: [push, pull_request]
jobs:
  build:
    if: github.repository == 'ubicenter/openfisca-us'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: openfisca_us
          environment-file: docs/book/environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Build  # Build Jupyter Book
        shell: bash -l {0}
        run: |
          pip install -e .
          jb build docs/book/.